# Default values for zipkin.
collector:
  replicaCount: 1
  maxReplicaCount: 3
  targetCPUUtilizationPercentage: 80
  imageVersion: 2
  sampleRate: 1.0
  probeStartupDelay: 200
  queryPort: 9411
  resources:
    ramMb: 900
    javaOptsHeap: 700
    cpuRequest: 100m
    cpuLimit: 300m

ui:
  replicaCount: 1
  imageVersion: 2
  probeStartupDelay: 300
  queryPort: 9411
  resources:
    ramMb: 900
    javaOptsHeap: 700
    cpuRequest: 150m
    cpuLimit: 200m

dependencies:
  enabled: true
  cron: "0 22 * * *"
  imageVersion: 1
  resources:
    ramMb: 1100
    javaOptsHeap: 700
    cpuRequest: 200m
    cpuLimit: 200m

configmap:
  name: zipkin
  contactPoints:
    name: zipkin
    key: cassandra.contactpoints
  username:
    name: zipkin
    key: cassandra.username
  localdc:
    name: zipkin
    key: cassandra.localdc

ingress:
  enabled: false
  class: "kong"
  host: placeholder
  path: /
  serviceName: zipkin-ui
  servicePort: 9411

storageMethod: elasticsearch

elasticsearch:
  hosts: elasticsearch.infra:9200
  dataHosts: elasticsearch-data.infra:9200

cassandra:
  username: zipkin
  password: zipkin
  contactPoints: zipkin-cassandra:9042
  localdc: datacenter1
  ensureSchema: false
  image: openzipkin/zipkin-cassandra
  probeStartupDelay: 120
  tag: 2
  replicas: 1
  pvSize: 20Gi
  resources:
    ramMb: 3500
    cpuRequest: 200m
    cpuLimit: 500m

node:
  cpus: 2
