# Default values for zipkin.
collector:
  replicaCount: 1
  maxReplicaCount: 3
  targetCPUUtilizationPercentage: 80
  imageVersion: 1.28.1
  sampleRate: 1.0
  probeStartupDelay: 150
  queryPort: 9411
  resources:
    ramMb: 500
    javaOptsHeap: 300
    cpuRequest: 150m
    cpuLimit: 200m

ui:
  replicaCount: 1
  imageVersion: 1.28.1
  probeStartupDelay: 150
  queryPort: 9411
  resources:
    ramMb: 500
    javaOptsHeap: 300
    cpuRequest: 200m
    cpuLimit: 200m

dependencies:
  enabled: false
  cron: "0 22 * * *"
  imageVersion: 1.6.1
  resources:
    ramMb: 300
    javaOptsHeap: 200
    cpuRequest: 200m
    cpuLimit: 200m

configmap:
  name: zipkin
  contactPoints:
    name: zipkin
    key: cassandra.contactpoints
  username:
    name: zipkin
    key: cassandra.username
  localdc:
    name: zipkin
    key: cassandra.localdc

storageMethod: elasticsearch

elasticsearch:
  hosts: elasticsearch.infra:9200

node:
  cpus: 1

ingress:
  enabled: false

