apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/nexus/src/main/fabric8/icon.png
  labels:
    expose: 'false'
    project: nexus
    provider: fabric8
    version: 2.2.311
  name: nexus
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    project: nexus
    provider: fabric8
  sessionAffinity: None
  type: ClusterIP
