apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ printf "%s-%s" .Release.Name .Values.Name | trunc 24 }}"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: "{{ printf "%s-%s-role" .Release.Name .Values.Name | trunc 24 }}"
rules:
  - apiGroups: ["sprinthive.com"]
    resources: ["routedservices"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: "{{ printf "%s-%s-clusterrole" .Release.Name .Values.Name | trunc 24 }}"
rules:
  - apiGroups: ["extensions"]
    resources: ["thirdpartyresources"]
    verbs: ["create", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: "{{ printf "%s-%s" .Release.Name .Values.Name | trunc 24 }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ printf "%s-%s-role" .Release.Name .Values.Name | trunc 24 }}"
subjects:
  - kind: ServiceAccount
    name: "{{ printf "%s-%s" .Release.Name .Values.Name | trunc 24 }}"
    namespace: {{.Release.Namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: "{{ printf "%s-%s" .Release.Name .Values.Name | trunc 24 }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ printf "%s-%s-clusterrole" .Release.Name .Values.Name | trunc 24 }}"
subjects:
  - kind: ServiceAccount
    name: "{{ printf "%s-%s" .Release.Name .Values.Name | trunc 24 }}"
    namespace: {{.Release.Namespace}}
