apiVersion: v1
kind: Service
metadata:
  name: {{.Values.Name}}
  labels:
    release: {{.Release.Name | quote }}
    app: {{.Values.Name}}
spec:
  selector:
    release: {{.Release.Name | quote }}
    app: {{.Values.Name}}
  ports:
  - name: http
    port: 80
    targetPort: 5601
    protocol: TCP
