apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-config
  labels:
    app: {{ template "fullname" . }}
data:
  custom-parsers.conf: |-
    [PARSER]
        Name         istio_proxy
        Format       regex
        Regex        ^\[(?<time>[^\]]*)](\[(?<code>[^\]]*)\])?(\[(?<level>[^\]]*)\])?(\[(?<module>[^\]]*)\])?(?<message>.*)$
        Time_Key     time
        Time_Format %Y-%m-%d %H:%M:%S
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z

    [PARSER]
        Name         docker_utf8
        Format       json
        Time_Key     time
        Time_Format  %Y-%m-%dT%H:%M:%S.%L
        Decode_Field_As   escaped_utf8    log

  fluent-bit.conf: |-
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf
        Parsers_File custom-parsers.conf

    [INPUT]
        Name             tail
        Path             /var/log/containers/*.log
        Exclude_Path     *istio*
        Parser           docker
        Tag              container_logs_text.*
        Refresh_Interval 5
        Mem_Buf_Limit    10MB
        Skip_Long_Lines  On
        DB               /var/tmp/fluent-bit.db

    [INPUT]
        Name             tail
        Path             /var/log/containers/*istio-proxy*.log
        Tag              istio_proxy_container_logs_text.*
        Parser           docker_utf8
        Refresh_Interval 5
        Mem_Buf_Limit    10MB
        Skip_Long_Lines  On
        DB               /var/tmp/fluent-bit-istio-proxy.db

    [INPUT]
        Name             tail
        Path             /var/log/containers/*istio-pilot*discovery*.log
        Tag              istio_generic_container_logs_json.*
        Parser           docker_utf8
        Refresh_Interval 5
        Mem_Buf_Limit    10MB
        Skip_Long_Lines  On
        DB               /var/tmp/fluent-bit-istio-generic.db

    [INPUT]
        Name             tail
        Path             /var/log/containers/*istio*mixer*.log
        Tag              istio_generic_container_logs_json.*
        Parser           docker_utf8
        Refresh_Interval 5
        Mem_Buf_Limit    10MB
        Skip_Long_Lines  On
        DB               /var/tmp/fluent-bit-istio-generic.db

    [INPUT]
        Name          tcp
        Listen        0.0.0.0
        Port          5170
        Chunk_Size    32
        Buffer_Size   64
        Mem_Buf_Limit 10MB
        Tag           app_logs

    [FILTER]
        Name   kubernetes
        Match  *container_logs_text*

    [FILTER]
        Name      kubernetes
        Match     *container_logs_json*
        Merge_Log On

    [FILTER]
        Name         parser
        Match        istio_proxy_container_logs_text.*
        Key_Name     log
        Parser       istio_proxy
        Reserve_Data True

    [FILTER]
        Name   modify
        Match  istio_generic_container_logs_json.*
        Rename msg message

{{ if eq .Values.backend.type "test" }}
    [OUTPUT]
        Name  file
        Match *
        Path /tmp/fluent-bit.log
{{ else if eq .Values.backend.type "forward" }}
    [OUTPUT]
        Name            forward
        Match           *
        Host            {{ .Values.backend.forward.host }}
        Port            {{ .Values.backend.forward.port }}
        Retry_Limit     False
{{ else if eq .Values.backend.type "es" }}
    [OUTPUT]
        Name            es
        Match           container_logs_text.*
        Host            {{ .Values.backend.es.host }}
        Port            {{ .Values.backend.es.port }}
        Logstash_Format On
        Retry_Limit     False
        Time_Key        @timestamp

    [OUTPUT]
        Name            es
        Match           *istio*
        Host            {{ .Values.backend.es.host }}
        Port            {{ .Values.backend.es.port }}
        Logstash_Format On
        Retry_Limit     False
        Time_Key        @timestamp
        Logstash_Prefix istio_logs

    [OUTPUT]
        Name            es
        Match           app_logs
        Host            {{ .Values.backend.es.host }}
        Port            {{ .Values.backend.es.port }}
        Logstash_Format On
        Retry_Limit     False
        Time_Key        @fb_timestamp
        Logstash_Prefix app_logs
{{- end }}
