apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluent-bit
  labels:
    app: {{ template "fullname" . }}
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      serviceAccount: fluent-bit
      containers:
      - name: fluent-bit
        image: "{{ .Values.image.fluent_bit.repository }}:{{ .Values.image.fluent_bit.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        env:
{{ toYaml .Values.env | indent 10 }}
        ports:
        - name: tcp-logs
          containerPort: 5170
          protocol: TCP
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: vartmp
          mountPath: /var/tmp
        - name: config
          mountPath: /fluent-bit/etc/fluent-bit.conf
          subPath: fluent-bit.conf
        - name: config
          mountPath: /fluent-bit/etc/custom-parsers.conf
          subPath: custom-parsers.conf
{{ if .Values.on_minikube }}
        - name: mnt
          mountPath: /mnt
          readOnly: true
{{ end }}
      terminationGracePeriodSeconds: 10
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: vartmp
        hostPath:
          path: /var/tmp
      - name: config
        secret:
          secretName: {{ template "fullname" . }}-config
{{ if .Values.on_minikube }}
      - name: mnt
        hostPath:
          path: /mnt
{{ end }}
