apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "fullname" . }}
spec:
  selector:
    app: {{ template "fullname" . }}
  ports:
  - name: http
    port: 5170
    targetPort: 5170
    protocol: TCP
