apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: "{{ printf "%s-%s" .Release.Name .Values.Name | trunc 24 }}"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    app: {{.Values.Component}}
spec:
  selector:
    matchLabels:
      app: {{.Values.Component}}
  template:
    metadata:
      labels:
        app: {{ .Values.Component }}
    spec:
      {{- if (not (empty .Values.ImagePullSecrets)) }}
      imagePullSecrets:
      {{- range .Values.ImagePullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
      - name: {{.Values.Name}}
        image: "{{ .Values.Image }}:{{ .Values.Tag }}"
        imagePullPolicy: {{.Values.ImagePullPolicy}}
        env:
          {{- if eq .Values.DefaultSSL.Override true }}
          - name: KONG_SSL_CERT
            value: "/usr/local/kong/ssl/default/{{ .Values.DefaultSSL.SSLCert }}"
          - name: KONG_SSL_CERT_KEY
            value: "/usr/local/kong/ssl/default/{{ .Values.DefaultSSL.SSLKey }}"
          {{- end }}
          - name: KONG_PROXY_ACCESS_LOG
            value: /dev/stdout
          - name: KONG_PROXY_ERROR_LOG
            value: /dev/stderr
          - name: KONG_ADMIN_ACCESS_LOG
            value: /dev/stdout
          - name: KONG_ADMIN_ERROR_LOG
            value: /dev/stderr
          - name: KONG_DATABASE
            value: {{.Values.KongDatabase}}
          - name: KONG_PG_HOST
            value: {{.Values.PostgresHost}}
          - name: KONG_PG_DATABASE
            value: kong
          - name: KONG_PG_USER
            value: kong
          - name: KONG_PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: kong-postgres
                key: postgresql-password
          - name: KONG_ADMIN_LISTEN
            value: 0.0.0.0:8001
          - name: KONG_PROXY_LISTEN
            value: "0.0.0.0:80, 0.0.0.0:443 ssl"
          - name: KONG_HOST_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: KONG_CUSTOM_PLUGINS
            value: jwtheaders
        ports:
        - name: admin
          containerPort: 8001
          protocol: TCP
        - name: proxy
          containerPort: 80
          {{- if eq .Values.HostPort true }}
          hostPort: 80
          {{- end }}
          protocol: TCP
        - name: proxy-ssl
          containerPort: 443
          {{- if eq .Values.HostPort true }}
          hostPort: 443
          {{- end }}
          protocol: TCP
        - name: surf-tcp
          containerPort: 7946
          protocol: TCP
        - name: surf-udp
          containerPort: 7946
          protocol: UDP
        livenessProbe:
          tcpSocket:
            port: 8001
          initialDelaySeconds: 90
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ping
            port: proxy-ssl
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 10
          {{- if eq .Values.DefaultSSL.Override true }}
        volumeMounts:
          - name: kong-default-tls
            mountPath: /usr/local/kong/ssl/default/
            readOnly: true
          {{- end }}
      volumes:
      {{- if eq .Values.DefaultSSL.Override true }}
      - name: kong-default-tls
        secret:
          defaultMode: 420
          secretName: kong-default-tls
      {{- end }}
