apiVersion: extensions/v1beta1
{{- if eq .Values.HostPort true }}
kind: DaemonSet
{{- else }}
kind: Deployment
{{- end }}
metadata:
  name: "{{ printf "%s-%s" .Release.Name .Values.Name | trunc 24 }}"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: {{.Values.Component}}
spec:
  {{- if eq .Values.HostPort false }}
  replicas: 1
  {{- end }}
  template:
    metadata:
      labels:
        component: {{.Values.Component}}
    spec:
      initContainers:
        - name: kong-migrate
          image: {{.Values.Image}}
          env:
            - name: KONG_DATABASE
              value: {{.Values.KongDatabase}}
            - name: KONG_CASSANDRA_CONTACT_POINTS
              value: {{.Values.CassandraContactPoints}}
            - name: KONG_CASSANDRA_KEYSPACE
              value: "{{ printf "%s_%s" .Release.Name .Values.Name | trunc 24 }}"
            - name: KONG_CASSANDRA_REPL_FACTOR
              value: "{{.Values.CassandraReplFactor}}"
            - name: KONG_DB_UPDATE_PROPAGATION
              value: "10"
            - name: KONG_CASSANDRA_SCHEMA_CONSENSUS_TIMEOUT
              value: "5000"
            - name: KONG_HOST_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          command: [ "/bin/sh", "-c", "KONG_CLUSTER_ADVERTISE=$(KONG_HOST_IP):7946 KONG_NGINX_DAEMON='off' kong migrations up" ]
        - name: prometheus-plugin-setup
          image: {{.Values.Image}}
          command: [ "/bin/sh", "-c", "sh /tmp/prometheus-plugin-setup/apply_config.sh" ]
          volumeMounts:
            - name: prometheus-plugin-setup
              mountPath: /tmp/prometheus-plugin-setup
            - name: plugin-extras
              mountPath: /usr/local/share/kong-extra-plugins
      containers:
      - name: {{.Values.Name}}
        image: {{.Values.Image}}
        imagePullPolicy: {{.Values.ImagePullPolicy}}
        env:
          - name: KONG_LUA_PACKAGE_PATH
            value: "/usr/local/share/kong-extra-plugins/?.lua;;"
          - name: KONG_CUSTOM_PLUGINS
            value: "prometheus"
          - name: KONG_DATABASE
            value: {{.Values.KongDatabase}}
          - name: KONG_CASSANDRA_CONTACT_POINTS
            value: {{.Values.CassandraContactPoints}}
          - name: KONG_CASSANDRA_KEYSPACE
            value: "{{ printf "%s_%s" .Release.Name .Values.Name | trunc 24 }}"
          - name: KONG_CASSANDRA_REPL_FACTOR
            value: "{{.Values.CassandraReplFactor}}"
          - name: KONG_DB_UPDATE_PROPAGATION
            value: "10"
          - name: KONG_CASSANDRA_SCHEMA_CONSENSUS_TIMEOUT
            value: "5000"
          - name: KONG_HOST_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
        command: [ "/bin/sh", "-c", "KONG_CLUSTER_ADVERTISE=$(KONG_HOST_IP):7946 KONG_NGINX_DAEMON='off' kong start" ]
        ports:
        - name: admin
          containerPort: 8001
          protocol: TCP
        - name: proxy
          containerPort: 8000
          {{- if eq .Values.HostPort true }}
          hostPort: 80
          {{- end }}
          protocol: TCP
        - name: proxy-ssl
          containerPort: 8443
          {{- if eq .Values.HostPort true }}
          hostPort: 443
          {{- end }}
          protocol: TCP
        - name: surf-tcp
          containerPort: 7946
          protocol: TCP
        - name: surf-udp
          containerPort: 7946
          protocol: UDP
        livenessProbe:
          tcpSocket:
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /status
            port: admin
          initialDelaySeconds: 30
          periodSeconds: 10
        volumeMounts:
          - name: plugin-extras
            mountPath: /usr/local/share/kong-extra-plugins
      volumes:
        - name: prometheus-plugin-setup
          configMap:
            name: prometheus-plugin-setup
        - name: plugin-extras
          emptyDir: {}