apiVersion: extensions/v1beta1
{{- if eq .Values.HostPort true }}
kind: DaemonSet
{{- else }}
kind: Deployment
{{- end }}
metadata:
  name: "{{ printf "%s-%s" .Release.Name .Values.Name | trunc 24 }}"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    app: {{.Values.Component}}
spec:
  {{- if eq .Values.HostPort false }}
  replicas: 1
  {{- end }}
  template:
    metadata:
      labels:
        app: {{.Values.Component}}
      {{- if eq .Values.IstioSidecar true }}
      annotations:
        sidecar.istio.io/status: '{"version":"c3a47039bf1299722cd788931e7474b29004f18a1eaf49db22ed1c58c818d46c","initContainers":["istio-init"],"containers":["istio-proxy"],"volumes":["istio-envoy","istio-certs"],"imagePullSecrets":null}'
      {{- end }}
    spec:
      {{- if eq .Values.IstioSidecar true }}
      initContainers:
      - args:
        - -p
        - "15001"
        - -u
        - "1337"
        - -m
        - REDIRECT
        - -i
        - 10.16.0.0/14
        - -x
        - ""
        - -b
        - 8001, 8000, 8443, 7946, 7946,
        - -d
        - ""
        image: docker.io/istio/proxy_init:0.8.0
        imagePullPolicy: IfNotPresent
        name: istio-init
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
      {{- end }}
      containers:
      - name: {{.Values.Name}}
        image: {{.Values.Image}}
        imagePullPolicy: {{.Values.ImagePullPolicy}}
        env:
          {{- if eq .Values.DefaultSSL.Override true }}
          - name: KONG_SSL_CERT
            value: /usr/local/kong/ssl/default/{{.Values.DefaultSSL.SSLCert}}
          - name: KONG_SSL_CERT_KEY
            value: /usr/local/kong/ssl/default/{{.Values.DefaultSSL.SSLKey}}
          {{- end }}
          - name: KONG_PROXY_ACCESS_LOG
            value: /dev/stdout
          - name: KONG_PROXY_ERROR_LOG
            value: /dev/stderr
          - name: KONG_ADMIN_ACCESS_LOG
            value: /dev/stdout
          - name: KONG_ADMIN_ERROR_LOG
            value: /dev/stderr
          - name: KONG_DATABASE
            value: {{.Values.KongDatabase}}
          - name: KONG_CASSANDRA_CONTACT_POINTS
            value: {{.Values.CassandraContactPoints}}
          - name: KONG_CASSANDRA_KEYSPACE
            value: "{{ printf "%s_%s" .Release.Name .Values.Name | trunc 24 }}"
          - name: KONG_CASSANDRA_REPL_FACTOR
            value: "{{.Values.CassandraReplFactor}}"
          - name: KONG_DB_UPDATE_PROPAGATION
            value: "10"
          - name: KONG_CASSANDRA_SCHEMA_CONSENSUS_TIMEOUT
            value: "5000"
          - name: KONG_ADMIN_LISTEN
            value: 0.0.0.0:8001
          - name: KONG_HOST_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
        ports:
        - name: admin
          containerPort: 8001
          protocol: TCP
        - name: proxy
          containerPort: 8000
          {{- if eq .Values.HostPort true }}
          hostPort: 80
          {{- end }}
          protocol: TCP
        - name: proxy-ssl
          containerPort: 8443
          {{- if eq .Values.HostPort true }}
          hostPort: 443
          {{- end }}
          protocol: TCP
        - name: surf-tcp
          containerPort: 7946
          protocol: TCP
        - name: surf-udp
          containerPort: 7946
          protocol: UDP
        livenessProbe:
          tcpSocket:
            port: 8001
          initialDelaySeconds: 90
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /status
            port: admin
          initialDelaySeconds: 90
          periodSeconds: 10
          {{- if eq .Values.DefaultSSL.Override true }}
          - name: kong-default-tls
            mountPath: /usr/local/kong/ssl/default/
            readOnly: true
          {{- end }}
      {{- if eq .Values.IstioSidecar true }}
      - args:
        - proxy
        - sidecar
        - --configPath
        - /etc/istio/proxy
        - --binaryPath
        - /usr/local/bin/envoy
        - --serviceCluster
        - istio-proxy
        - --drainDuration
        - 45s
        - --parentShutdownDuration
        - 1m0s
        - --discoveryAddress
        - istio-pilot.istio-system:15007
        - --discoveryRefreshDelay
        - 10s
        - --zipkinAddress
        - zipkin.infra:9411
        - --connectTimeout
        - 10s
        - --statsdUdpAddress
        - istio-statsd-prom-bridge.istio-system:9125
        - --proxyAdminPort
        - "15000"
        - --controlPlaneAuthPolicy
        - NONE
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ISTIO_META_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ISTIO_META_INTERCEPTION_MODE
          value: REDIRECT
        image: quay.io/sprinthive/proxyv2:e80a6e4058543eed75a5f4b093f87e105cfde038
        imagePullPolicy: IfNotPresent
        name: istio-proxy
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          privileged: false
          readOnlyRootFilesystem: true
          runAsUser: 1337
        volumeMounts:
        - mountPath: /etc/istio/proxy
          name: istio-envoy
        - mountPath: /etc/certs/
          name: istio-certs
          readOnly: true
      {{- end }}
      volumes:
      {{- if eq .Values.DefaultSSL.Override true }}
      - name: kong-default-tls
        secret:
          defaultMode: 420
          secretName: kong-default-tls
      {{- end }}
      {{- if eq .Values.IstioSidecar true }}
      - emptyDir:
          medium: Memory
        name: istio-envoy
      - name: istio-certs
        secret:
          optional: true
          secretName: istio.default
      {{- end }}
