apiVersion: extensions/v1beta1
{{- if eq .Values.HostPort true }}
kind: DaemonSet
{{- else }}
kind: Deployment
{{- end }}
metadata:
  name: "{{ printf "%s-%s" .Release.Name .Values.Name | trunc 24 }}"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    app: {{.Values.Component}}
spec:
  {{- if eq .Values.HostPort false }}
  replicas: {{ .Values.Replicas }}
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ .Values.Component }}
    spec:
      {{- if eq .Values.IstioSidecar.enabled true }}
      initContainers:
      - args:
        - -p
        - "15001"
        - -u
        - "1337"
        - -m
        - REDIRECT
        - -i
        - 10.16.0.0/14
        - -x
        - ""
        - -d
        - ""
        image: {{ .Values.IstioSidecar.hub }}/proxy_init:{{ .Values.IstioSidecar.tag }}
        imagePullPolicy: IfNotPresent
        name: istio-init
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
      {{- end }}
      containers:
      - name: {{.Values.Name}}
        image: {{.Values.Image}}
        imagePullPolicy: {{.Values.ImagePullPolicy}}
        env:
          {{- if eq .Values.DefaultSSL.Override true }}
          - name: KONG_SSL_CERT
            value: "/usr/local/kong/ssl/default/{{ .Values.DefaultSSL.SSLCert }}"
          - name: KONG_SSL_CERT_KEY
            value: "/usr/local/kong/ssl/default/{{ .Values.DefaultSSL.SSLKey }}"
          {{- end }}
          - name: KONG_PROXY_ACCESS_LOG
            value: /dev/stdout
          - name: KONG_PROXY_ERROR_LOG
            value: /dev/stderr
          - name: KONG_ADMIN_ACCESS_LOG
            value: /dev/stdout
          - name: KONG_ADMIN_ERROR_LOG
            value: /dev/stderr
          - name: KONG_DATABASE
            value: {{.Values.KongDatabase}}
          - name: KONG_PG_HOST
            value: {{.Values.PostgresHost}}
          - name: KONG_PG_DATABASE
            value: kong
          - name: KONG_PG_USER
            value: kong
          - name: KONG_PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: kong-postgres
                key: postgresql-password
          - name: KONG_ADMIN_LISTEN
            value: 0.0.0.0:8001
          - name: KONG_PROXY_LISTEN
            value: "0.0.0.0:80, 0.0.0.0:443 ssl"
          - name: KONG_HOST_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
        ports:
        - name: admin
          containerPort: 8001
          protocol: TCP
        - name: proxy
          containerPort: 80
          {{- if eq .Values.HostPort true }}
          hostPort: 80
          {{- end }}
          protocol: TCP
        - name: proxy-ssl
          containerPort: 443
          {{- if eq .Values.HostPort true }}
          hostPort: 443
          {{- end }}
          protocol: TCP
        - name: surf-tcp
          containerPort: 7946
          protocol: TCP
        - name: surf-udp
          containerPort: 7946
          protocol: UDP
        livenessProbe:
          tcpSocket:
            port: 8001
          initialDelaySeconds: 90
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /status
            port: admin
          initialDelaySeconds: 90
          periodSeconds: 10
          {{- if eq .Values.DefaultSSL.Override true }}
        volumeMounts:
          - name: kong-default-tls
            mountPath: /usr/local/kong/ssl/default/
            readOnly: true
          {{- end }}
      {{- if eq .Values.IstioSidecar.enabled true }}
      - args:
        - proxy
        - sidecar
        - --configPath
        - /etc/istio/proxy
        - --binaryPath
        - /usr/local/bin/envoy
        - --serviceCluster
        - istio-proxy
        - --drainDuration
        - 45s
        - --parentShutdownDuration
        - 1m0s
        - --discoveryAddress
        - istio-pilot.istio-system:15007
        - --discoveryRefreshDelay
        - 10s
        - --zipkinAddress
        - zipkin.infra:9411
        - --connectTimeout
        - 10s
        - --statsdUdpAddress
        - istio-statsd-prom-bridge.istio-system:9125
        - --proxyAdminPort
        - "15000"
        - --controlPlaneAuthPolicy
        - NONE
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ISTIO_META_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ISTIO_META_INTERCEPTION_MODE
          value: REDIRECT
        image: {{ .Values.IstioSidecar.hub }}/proxyv2:{{ .Values.IstioSidecar.tag }}
        imagePullPolicy: IfNotPresent
        name: istio-proxy
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          privileged: false
          readOnlyRootFilesystem: true
          runAsUser: 1337
        volumeMounts:
        - mountPath: /etc/istio/proxy
          name: istio-envoy
        - mountPath: /etc/certs/
          name: istio-certs
          readOnly: true
      {{- end }}
      volumes:
      {{- if eq .Values.DefaultSSL.Override true }}
      - name: kong-default-tls
        secret:
          defaultMode: 420
          secretName: kong-default-tls
      {{- end }}
      {{- if eq .Values.IstioSidecar.enabled true }}
      - emptyDir:
          medium: Memory
        name: istio-envoy
      - name: istio-certs
        secret:
          optional: true
          secretName: istio.default
      {{- end }}
