apiVersion: v1
kind: Service
metadata:
  name: kong-admin
spec:
  type: ClusterIP
  ports:
  - name: kong-admin
    port: 8001
    targetPort: 8001
    protocol: TCP
  selector:
    component: {{.Values.Component}}
