apiVersion: v1
kind: Service
metadata:
  name: kong-proxy
spec:
  type: ClusterIP
  ports:
  - name: kong-proxy
    port: 8080
    targetPort: 8000
    protocol: TCP
  selector:
    component: {{.Values.Component}}
