Component: elasticsearch
Name: es
Image: quay.io/sprinthive/elasticsearch:jdk-base
ImagePullPolicy: IfNotPresent
ClusterName: kube-es
Plugins: ""
SearchGuard:
  Enabled: false
  Plugin: com.floragunn:search-guard-5:5.4.1-12

Master:
  Role: master
  Replicas: 1
  MinimumMasters: 1
  JavaOpts: "-Xms450m -Xmx450m"
  CpuRequests: "0.25"
  CpuLimits: "0.25"
  MemoryRequests: "800Mi"
  MemoryLimits: "800Mi"
  LivenessTest:
    InitialDelaySecs: 600
    TimeoutSecs: 1
  VolumeClaimTemplate:
    Enabled: false
    StorageClass: gp2
    RequestedStorage: 1Gi

Client:
  Role: client
  Replicas: 1
  JavaOpts: "-Xms1100m -Xmx1100m"
  CpuRequests: "0.8"
  CpuLimits: "1.2"
  MemoryRequests: "1.5Gi"
  MemoryLimits: "1.5Gi"
  LivenessTest:
    InitialDelaySecs: 600
    TimeoutSecs: 1
  VolumeClaimTemplate:
    Enabled: false
    StorageClass: gp2
    RequestedStorage: 1Gi

Data:
  Role: data
  Replicas: 3
  JavaOpts: "-Xms2500m -Xmx2500m"
  CpuRequests: "1"
  CpuLimits: "1.5"
  MemoryRequests: "5.5Gi"
  MemoryLimits: "5.5Gi"
  LivenessTest:
    InitialDelaySecs: 600
    TimeoutSecs: 1
  VolumeClaimTemplate:
    Enabled: true
    StorageClass: gp2
    RequestedStorage: 100Gi

Sgadmin:
  Role: sgadmin
  Image: quay.io/sprinthive/searchguard-init:v1.0.1

Service:
  Name: elasticsearch

DiscoveryService:
  Name: elasticsearch-discovery
