Component: elasticsearch
Name: es
Image: quay.io/sprinthive/docker-elasticsearch:dev
ImagePullPolicy: IfNotPresent
ClusterName: kube-es
Plugins: ""
SearchGuard:
  Enabled: false
  Plugin: com.floragunn:search-guard-5:5.4.1-12

Master:
  Role: master
  Replicas: 1
  MinimumMasters: 1
  JavaOpts: "-Xms300m -Xmx300m"
  CpuRequests: "250m"
  CpuLimits: "250m"
  MemoryRequests: "512Mi"
  MemoryLimits: "712Mi"
  LivenessTest:
    InitialDelaySecs: 600
    TimeoutSecs: 1
  VolumeClaimTemplate:
    Enabled: false
    StorageClass: standard
    RequestedStorage: 1Gi

Client:
  Role: client
  Replicas: 1
  JavaOpts: "-Xms300m -Xmx300m"
  CpuRequests: "250m"
  CpuLimits: "250m"
  MemoryRequests: "512Mi"
  MemoryLimits: "712Mi"
  LivenessTest:
    InitialDelaySecs: 600
    TimeoutSecs: 1
  VolumeClaimTemplate:
    Enabled: false
    StorageClass: standard
    RequestedStorage: 1Gi

Data:
  Role: data
  Replicas: 1
  JavaOpts: "-Xms300m -Xmx300m"
  CpuRequests: "250m"
  CpuLimits: "250m"
  MemoryRequests: "512Mi"
  MemoryLimits: "712Mi"
  LivenessTest:
    InitialDelaySecs: 600
    TimeoutSecs: 1
  VolumeClaimTemplate:
    Enabled: true
    StorageClass: magnetic
    RequestedStorage: 50Gi

Sgadmin:
  Role: sgadmin
  Image: quay.io/sprinthive/searchguard-init:v1.0.1

Service:
  Name: elasticsearch

DiscoveryService:
  Name: elasticsearch-discovery
