apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "name" . }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ template "name" . }}
rules:
  - apiGroups: ["extensions"]
    resources: ["thirdpartyresources", "customresourcedefinitions"]
    verbs: ["create", "get"]
  - apiGroups: ["platform.koli.io"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["extensions"]
    resources: ["ingresses"]
    verbs: ["get", "watch", "list", "patch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "patch", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["patch", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ template "name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "name" . }}
    namespace: {{ .Release.Namespace }}
