{{- if eq .Values.clusterProfile "production"}}
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "fullname" $ }}
  {{- template "labels" . }}
spec:
  serviceName: {{ template "name" $ }}
  replicas: {{ .Values.production.config.cluster_size }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" $ }}
    spec:
{{- if .Values.selector }}
{{ toYaml .Values.selector | indent 6 }}
{{- end }}
      containers:
      - name: {{ template "fullname" $ }}
        image: "{{ .Values.image.repo }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        resources:
{{ toYaml .Values.production.resources | indent 10 }}
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        env:
        {{- $seed_size := default 1 .Values.production.config.seed_size | int -}}
        {{- $global := . }}
        - name: CASSANDRA_SEEDS
          value: "{{- range $i, $e := until $seed_size }}{{ template "fullname" $global }}-{{ $i }}.{{ template "name" $global }}.{{ $global.Release.Namespace }}.svc.cluster.local,{{- end }}"
        - name: MAX_HEAP_SIZE
          value: {{ default "512M" .Values.production.config.max_heap_size | quote }}
        - name: HEAP_NEWSIZE
          value: {{ default "512M" .Values.production.config.heap_new_size | quote }}
        - name: CASSANDRA_ENDPOINT_SNITCH
          value: {{ default "SimpleSnitch" .Values.production.config.endpoint_snitch | quote }}
        - name: CASSANDRA_CLUSTER_NAME
          value: {{ default "Cassandra" .Values.config.cluster_name | quote }}
        - name: CASSANDRA_DC
          value: {{ default "DC1" .Values.production.config.dc_name | quote }}
        - name: CASSANDRA_RACK
          value: {{ default "RAC1" .Values.production.config.rack_name | quote }}
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        livenessProbe:
          exec:
            command: [ "/bin/sh", "-c", "nodetool status" ]
          initialDelaySeconds: 90
          periodSeconds: 30
        readinessProbe:
          exec:
            command: [ "/bin/sh", "-c", "nodetool status | grep -E \"^UN\\s+${POD_IP}\"" ]
          initialDelaySeconds: 90
          periodSeconds: 30
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "PID=$(pidof java) && kill $PID && while ps -p $PID > /dev/null; do sleep 1; done"]
        ports:
        - name: intra
          containerPort: 7000
        - name: tls
          containerPort: 7001
        - name: jmx
          containerPort: 7199
        - name: cql
          containerPort: {{ default 9042 .Values.config.ports.cql }}
        - name: thrift
          containerPort: {{ default 9160 .Values.config.ports.thrift }}
        volumeMounts:
        - name: data
          mountPath: /var/lib/cassandra
{{- if not .Values.production.persistence.enabled }}
      volumes:
      - name: data
        emptyDir: {}
{{- else }}
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: {{ template "fullname" $ }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
      annotations:
      {{- if .Values.production.persistence.storageClass }}
        volume.beta.kubernetes.io/storage-class: {{ .Values.production.persistence.storageClass | quote }}
      {{- else }}
        volume.alpha.kubernetes.io/storage-class: default
      {{- end }}
    spec:
      accessModes:
        - {{ .Values.production.persistence.accessMode | quote }}
      resources:
        requests:
          storage: {{ .Values.production.persistence.size | quote }}
{{- end }}
{{- end }}
