# Default values for jenkins.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

Master:
  ServiceType: ClusterIP
  InstallPlugins:
      - kubernetes:1.12.6
      - kubernetes-pipeline-devops-steps:1.5
      - kubernetes-pipeline-steps:1.5
      - workflow-aggregator:2.6
      - credentials-binding:1.16
      - git:3.9.1
      - amazon-ecr:1.6
      - google-oauth-plugin:0.6
      - google-container-registry-auth:0.3
      - bitbucket:1.1.8
      - cloudbees-bitbucket-branch-source:2.2.12
      - slack:2.3
      - global-slack-notifier:1.3
# Used to approve a list of groovy functions in pipelines used the script-security plugin. Can be viewed under /scriptApproval
  ScriptApproval:
     - staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods invokeMethod java.lang.Object java.lang.String java.lang.Object

  #   - "method groovy.json.JsonSlurperClassic parseText java.lang.String"
  #   - "new groovy.json.JsonSlurperClassic"
# List of groovy init scripts to be executed during Jenkins master start
  InitScripts:
     - |
        import org.jenkinsci.plugins.workflow.libs.*;
        import jenkins.plugins.git.GitSCMSource;
        import java.util.Collections;

        GlobalLibraries globalLibraries = GlobalLibraries.get();

        LibraryConfiguration shLibrary = new LibraryConfiguration("github.com/SprintHive/sprinthive-pipeline-library", new SCMSourceRetriever(new GitSCMSource(null, "https://github.com/SprintHive/sprinthive-pipeline-library.git", "", "origin", "+refs/heads/*:refs/remotes/origin/*", "*", "", true)));
        shLibrary.setDefaultVersion("master");
        shLibrary.setAllowVersionOverride(true);

        globalLibraries.setLibraries(Collections.singletonList(shLibrary));
  Ingress:
    Annotations:
      kubernetes.io/ingress.class: kong

Persistence:
  Size: 5Gi

rbac:
  install: true
  # RBAC api version (currently either v1beta1 or v1alpha1)
  apiVersion: v1beta1
  # Cluster role reference
  roleRef: jenkins
  roleBindingKind: RoleBinding
