{{if eq .Values.storageMethod "cassandra"}}
apiVersion: v1
kind: Secret
metadata:
  name: zipkin
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "name" . }}
  # This declares the resource to be a hook. By convention, we also name the
  # file "pre-install-XXX.yaml", but Helm itself doesn't care about file names.
type: Opaque
data:
  cassandra.password: {{ b64enc .Values.cassandra.password }}
{{ end }}
