apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Values.Name }}-configure"
spec:
  serviceAccountName: {{.Values.Component}}
  containers:
    - name: "{{ .Values.Name }}-configure"
      image: appropriate/curl:latest
      imagePullPolicy: {{ .Values.ImagePullPolicy }}
      command:
        - "sh"
        - "-c"
        - "until curl http://{{ .Values.Service.Name }}:9200/_cluster/health?wait_for_status=yellow; do echo waiting for availability of elasticsearch; sleep 2; done; curl -XPUT http://{{ .Values.Service.Name }}:9200/_template/all -H 'content_type: application/json' -d'{\"template\": \"*\", \"settings\": {\"number_of_shards\": 5, \"number_of_replicas\": 2}}'"
  restartPolicy: Never
