{{- if eq .Values.SearchGuard.Enabled true}}
apiVersion: v1
kind: Pod
metadata:
  name: "{{ printf "%s-%s-%s" .Values.Name .Values.Sgadmin.Role .Release.Name | trunc 24 }}"
spec:
  serviceAccountName: {{.Values.Component}}
  containers:
    - name: "{{ printf "%s-%s-%s" .Values.Name .Values.Sgadmin.Role .Release.Name | trunc 24 }}"
      image: {{.Values.Sgadmin.Image}}
      imagePullPolicy: {{.Values.ImagePullPolicy}}
      env:
        - name: DISCOVERY_SERVICE
          value: {{.Values.DiscoveryService.Name}}
        - name: KEYSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: es-{{.Values.Sgadmin.Role}}-transport-tls
              key: key-password
        - name: TRUSTSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: es-{{.Values.Sgadmin.Role}}-transport-tls
              key: key-password
      volumeMounts:
        - name: sgadmin-keys
          mountPath: /keys
          readOnly: true
        - name: sgadmin-config
          mountPath: /sgconfig
  restartPolicy: Never
  volumes:
    - name: sgadmin-keys
      secret:
        secretName: es-{{.Values.Sgadmin.Role}}-transport-tls
    - name: sgadmin-config
      configMap:
        name: sgadmin-config
{{- end}}
