apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.Component}}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: {{.Values.Component}}
