{{- if eq .Values.clusterProfile "local"}}
# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  {{- if .Values.serviceAnnotations }}
{{ toYaml .Values.serviceAnnotations | indent 4 }}
  {{- end }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "name" . }}
spec:
  type: NodePort
  ports:
  - port: {{ .Values.port }}
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
{{- end }}