{{- if and (eq .Values.clusterProfile "local") (and (.Values.local.auth.enabled) (not .Values.local.auth.existingAdminSecret)) -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "adminSecret" . }}
type: Opaque
data:
  user: {{ .Values.local.auth.adminUser | b64enc }}
  password: {{ .Values.local.auth.adminPassword | b64enc }}
{{- end -}}
