Component: kong
Name: kong
Image: eu.gcr.io/honeycomb-release/kong
Tag: 0.13.0.1
ImagePullPolicy: IfNotPresent
ImagePullSecrets: []
KongDatabase: postgres
PostgresHost: kong-postgres
HostPort: false

Replicas: 3

ProxyService:
  Type: LoadBalancer
  HttpEnabled: true
  Annotations: null

DefaultSSL:
  Override: false
  SSLCert: kong-default.crt
  SSLKey: kong-default.key
