Component: kong
Name: kong
Image: kong:0.10.3
ImagePullPolicy: IfNotPresent
KongDatabase: cassandra
CassandraContactPoints: kong-cassandra
CassandraReplFactor: 1

ProxyService:
  Type: ClusterIP
  HttpEnabled: true
