Component: kong
Name: kong
Image: kong:0.10.3
ImagePullPolicy: IfNotPresent
KongDatabase: cassandra
CassandraContactPoints: kong-cassandra.infra.svc.cluster.local
CassandraReplFactor: 2

ProxyService:
  Type: ClusterIP
  HttpEnabled: true
