Component: kong
Name: kong
Image: kong:0.13.0
ImagePullPolicy: IfNotPresent
KongDatabase: cassandra
CassandraContactPoints: kong-cassandra.infra.svc.cluster.local
CassandraReplFactor: 2
HostPort: false
IstioSidecar:
  enabled: false
  hub: gcr.io/istio-release
  tag: release-1.0-latest-daily

Replicas: 3

ProxyService:
  Type: LoadBalancer
  HttpEnabled: true

DefaultSSL:
  Override: false
  SSLCert: kong-default.crt
  SSLKey: kong-default.key
