Component: kong
Name: kong
Image: kong:0.13.0
Registry: docker.io
ImagePullPolicy: IfNotPresent
ImagePullSecrets: []
KongDatabase: postgres
PostgresHost: kong-postgres
HostPort: false
IstioSidecar:
  enabled: false
  hub: docker.io/istio-release
  tag: release-1.0-latest-daily

Replicas: 3

ProxyService:
  Type: LoadBalancer
  HttpEnabled: true
  Annotations: null

DefaultSSL:
  Override: false
  SSLCert: kong-default.crt
  SSLKey: kong-default.key
