Component: kong
Name: kong
Image: kong:0.11.1-alpine
ImagePullPolicy: IfNotPresent
KongDatabase: cassandra
CassandraContactPoints: kong-cassandra.infra.svc.cluster.local
CassandraReplFactor: 2
HostPort: false

ProxyService:
  Type: ClusterIP
  HttpEnabled: true
