{{- if and (eq .Values.clusterProfile "production") (and (.Values.production.auth.enabled) (not .Values.production.auth.existingKeySecret)) -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "keySecret" . }}
type: Opaque
data:
  key.txt: {{ .Values.production.auth.key | b64enc }}
{{- end -}}

